name: publish build to PyPI
on:
   push:
    branches: 
      - main
      - build_and_publish

jobs:
  publish_wheel_with_c:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-latest, windows-latest]
        exclude:
          - os: ubuntu-22.04-arm
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    env:
      REQUIRE_SPEEDUPS: 1
    if: "contains(github.event.head_commit.message, 'Release Version')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Add requirements
        run: poetry install -v
      - name: Build package
        run: poetry build -f wheel
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      
  publish_sdist:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release Version')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Add requirements
        run: poetry install -v
      - name: Build package
        run: poetry build -f sdist
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
    
