name: poetry install for numba
on:
   - push

env:
  SEAMLESS_TEST_TARGET_PLATFORM: "Numba"

jobs:
  testing:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install --with numba
      - name: Test package
        run: poetry run pytest 
