name: publish wheels to PyPI
on:
   push:
    branches: 
      - main

jobs:
  publish_sdist:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release Version')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Add requirements
        run: poetry install -v
      - name: Build package
        run: poetry build -f sdist
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
    
