name: check with package installed from build
on:
   - push
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - uses: actions/upload-artifact@master
        with:
          name: Build_SDist
          path: dist/seamless_entropy-*.tar.gz
      - uses: actions/upload-artifact@master
        with:
          name: Build_Wheel
          path: dist/seamless_entropy-*.whl
  
  install_and_test:
    strategy:
      fail-fast: false
      matrix:
        package:
          - {"location": "test_packages/entropy_numba_from_build"}
          - {"location": "test_packages/entropy_numba_from_build"}
          - {"location": "test_packages/entropy_numba_from_build"}
        build: 
          - {"glob": "seamless_entropy-*.tar.gz", "artefact": "Build_SDist"}
          - {"glob": "seamless_entropy-*.whl", "artefact": "Build_Wheel"}
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ${{ matrix.package.location }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/download-artifact@master
        with:
          name: ${{ matrix.build.artefact }}
          path: ${{ matrix.package.location }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Install sdist package for seamless_entropy
        run: poetry run pip install ${{ matrix.build.glob }}
      - name: Test package
        run: poetry run pytest 
